# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: DestinyNet paper notebook
author: "Songtao Jiang, Ziwei Xue"
copyright: "2023"  # Copyright year to be placed in the footer
# logo: logo.png

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/test_repo/
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
